In [1]:
import torch

In [4]:
x = torch.rand((2, 3))
x

tensor([[0.0631, 0.5356, 0.0471],
        [0.0305, 0.5123, 0.3020]])

In [5]:
# permutation of tensors
torch.einsum('ij->ji', x)

tensor([[0.0631, 0.0305],
        [0.5356, 0.5123],
        [0.0471, 0.3020]])

In [6]:
# Summantion
torch.einsum('ij->', x)

tensor(1.4906)

In [7]:
# Column sum
torch.einsum('ij->j', x)

tensor([0.0936, 1.0479, 0.3492])

In [8]:
# Row sum
torch.einsum('ij->i', x)

tensor([0.6458, 0.8449])

In [13]:
# Matrix-vector multiplication
v = torch.rand((1, 3))

# (2, 3) MM (1, 3) -> (2, 3)
torch.einsum('ij,jk->ik', x, v)

# (2, 3) MM (3, 1) -> (2, 1)
torch.einsum('ij,kj->ik', x, v)

tensor([[0.2514],
        [0.4435]])

In [14]:
# Matrix-vector multiplication
# x.mm(x.t())

torch.einsum("ij,kj->ik", x, x)

tensor([[0.2930, 0.2905],
        [0.2905, 0.3546]])

In [15]:
# Dot product first row with first row of matrix
torch.einsum('i,i->', x[0], x[0])

tensor(0.2930)

In [16]:
# Dot product with matrix
torch.einsum('ij,ij->', x, x)

tensor(0.6476)

In [17]:
# Hadamard product (element-wise multiplication)
torch.einsum('ij,ij->ij', x, x)

tensor([[0.0040, 0.2868, 0.0022],
        [0.0009, 0.2625, 0.0912]])

In [19]:
# Outer product
a = torch.rand((3))
b = torch.rand((5))
torch.einsum('i,j->ij', a, b)

tensor([[0.1622, 0.2460, 0.0158, 0.0561, 0.3313],
        [0.3198, 0.4851, 0.0311, 0.1107, 0.6535],
        [0.3782, 0.5736, 0.0368, 0.1309, 0.7727]])

In [22]:
# Batch matrix multiplication
a = torch.rand((3,2,5))
b = torch.rand((3,5,3))
torch.einsum('ijk,ikl->ijl', a, b).shape

torch.Size([3, 2, 3])

In [26]:
# Matrix diagonal
x = torch.rand((3,3))
print(x)
torch.einsum('ii->', x)

tensor([[0.4406, 0.0199, 0.8760],
        [0.7236, 0.8195, 0.9224],
        [0.5149, 0.1915, 0.2748]])


tensor(1.5349)

In [29]:
# Matrix trace
torch.einsum('ii->i', x)

tensor([0.4406, 0.8195, 0.2748])