In [55]:
import torch

## Torch Initialization

In [56]:
my_tensor = torch.tensor(
    [[1,2,3,], [4,5,6]],
    dtype=torch.float32,
    requires_grad=True
)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [57]:
my_tensor.dtype

torch.float32

In [58]:
my_tensor.device

device(type='cpu')

In [59]:
my_tensor.shape

torch.Size([2, 3])

In [60]:
my_tensor.requires_grad

True

In [61]:
### Other common initialization methods

In [62]:
x = torch.empty(size=(3,3))
x

tensor([[4.1783e-34, 0.0000e+00, 4.3415e-34],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.5835e-43, 0.0000e+00, 3.6677e-34]])

In [63]:
x = torch.zeros((3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [64]:
x = torch.rand((3,3))
x

tensor([[0.7884, 0.2992, 0.1531],
        [0.7504, 0.6837, 0.1330],
        [0.1285, 0.2319, 0.9330]])

In [65]:
x = torch.ones((3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [66]:
x = torch.eye(5,5)
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [67]:
x = torch.arange(0, 5, 1)
x

tensor([0, 1, 2, 3, 4])

In [68]:
x = torch.linspace(0.1, 1, 10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [69]:
x = torch.empty(size=(1,5)).normal_(mean=0, std=1)
x

tensor([[-0.6667,  0.1378, -0.5116, -1.1875,  0.1092]])

In [70]:
x = torch.empty(size=(1,5)).uniform_(0,1)
x

tensor([[0.5742, 0.0864, 0.6802, 0.9432, 0.3096]])

In [71]:
x = torch.diag(torch.tensor([3,1,5]))
x

tensor([[3, 0, 0],
        [0, 1, 0],
        [0, 0, 5]])

# Datatype conversion

In [72]:
t = torch.arange(4)
t

tensor([0, 1, 2, 3])

In [73]:
t.bool()

tensor([False,  True,  True,  True])

In [74]:
t.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [75]:
t.long()

tensor([0, 1, 2, 3])

In [76]:
t.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [77]:
t.float().dtype

torch.float32

In [78]:
t.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [79]:
import numpy as np

In [80]:
np_arr = np.zeros((5,5))
t = torch.from_numpy(np_arr)
t

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [81]:
np_arr = t.numpy()

# Tensor math and comparision

In [82]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [83]:
z1 = torch.empty(3)
torch.add(x,y, out=z1)
z1

tensor([10., 10., 10.])

In [84]:
z2 = torch.add(x, y)
z2

tensor([10, 10, 10])

In [85]:
z = x+y
z

tensor([10, 10, 10])

In [86]:
z = x-y
z

tensor([-8, -6, -4])

In [87]:
z = torch.true_divide(x, y)
z

tensor([0.1111, 0.2500, 0.4286])

In [88]:
t = torch.zeros(3)
t.add_(x)

tensor([1., 2., 3.])

In [89]:
x

tensor([1, 2, 3])

In [90]:
# Exponentiation
x.pow(2), x**2

(tensor([1, 4, 9]), tensor([1, 4, 9]))

In [91]:
# Simple comparison
x>0, x<0

(tensor([True, True, True]), tensor([False, False, False]))

In [92]:
# Matrix multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1, x2)
x3

tensor([[1.1967, 1.0014, 0.6482],
        [1.6595, 1.4151, 1.0735]])

In [93]:
x3 == x1.mm(x2)

tensor([[True, True, True],
        [True, True, True]])

In [94]:
x3 == x1 @ x2

tensor([[True, True, True],
        [True, True, True]])

In [95]:
# Matrix exponentiation
matrix_exp = torch.diag(torch.arange(1, 4))
matrix_exp.matrix_power(3)

tensor([[ 1,  0,  0],
        [ 0,  8,  0],
        [ 0,  0, 27]])

In [96]:
# Element wise multiplication
print(x, y)
z = x * y
print(z)

tensor([1, 2, 3]) tensor([9, 8, 7])
tensor([ 9, 16, 21])


In [97]:
# Dot product
z = torch.dot(x, y)
z

tensor(46)

In [98]:
# Batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

t1 = torch.rand((batch, n, m))
t2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(t1, t2) # (batch, n, p)

In [99]:
out_bmm.shape

torch.Size([32, 10, 30])

In [100]:
# Example of Broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

x1-x2

tensor([[-0.8552,  0.8787,  0.4079, -0.0160,  0.0417],
        [-0.8413,  0.3140,  0.4355, -0.1237,  0.3522],
        [-0.1748,  0.4578,  0.4246, -0.8692,  0.0063],
        [-0.3492,  0.3348,  0.1398, -0.7734,  0.7315],
        [-0.2350,  0.3715, -0.0113, -0.0606,  0.2598]])

In [101]:
x1 ** x2

tensor([[0.0015, 0.9964, 0.9049, 0.9222, 0.7775],
        [0.0266, 0.9534, 0.9130, 0.8207, 0.9003],
        [0.7197, 0.9685, 0.9099, 0.0765, 0.7539],
        [0.5587, 0.9559, 0.8049, 0.1803, 0.9815],
        [0.6650, 0.9600, 0.7153, 0.8803, 0.8727]])

In [102]:
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x); print(abs_x)
z = torch.argmax(x, dim=0); print(z)
z = torch.argmin(x, dim=0)

tensor([1, 2, 3])
tensor(2)


In [103]:
torch.mean(x.float(), dim=0)

tensor(2.)

In [104]:
torch.eq(x, y)

tensor([False, False, False])

In [105]:
print(y)
torch.sort(y, dim=0, descending=False)

tensor([9, 8, 7])


torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))

In [106]:
torch.clamp(torch.arange(10), min=3, max=7)

tensor([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [107]:
x = torch.tensor([1,0,1,1,1,1], dtype=torch.bool)
torch.any(x)

tensor(True)

In [108]:
torch.all(x)

tensor(False)

# Tensor indexing

In [109]:
batch_size = 10
features = 25

In [111]:
x = torch.rand((batch_size, features))
x.shape

torch.Size([10, 25])

In [112]:
x[0].shape, x[:, 0].shape, x[2, 0:10].shape

(torch.Size([25]), torch.Size([10]), torch.Size([10]))

In [113]:
x = torch.arange(10)
indices = [2,5,8]
x[indices]

tensor([2, 5, 8])

In [114]:
x = torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
x[rows, cols]

tensor([0.1443, 0.3891])

In [115]:
x = torch.arange(10)
x[(x<2) | (x>8)]

tensor([0, 1, 9])

In [117]:
x[x.remainder(2) == 0]

tensor([0, 2, 4, 6, 8])

In [118]:
torch.where(x > 5, x, x*2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [119]:
torch.tensor([0,0,1,2,2,4,3]).unique()

tensor([0, 1, 2, 3, 4])

In [120]:
x.ndimension()

1

In [121]:
x.numel()

10

In [123]:
x.nelement()

10

In [125]:
x.nelement?

# Torch reshaping

In [126]:
x = torch.arange(9)

In [127]:
x.view(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [128]:
x.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [129]:
x.reshape(3,3).t()

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [130]:
x.reshape(3,3).T

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [131]:
x = torch.arange(10)

In [132]:
x.unsqueeze(0).shape

torch.Size([1, 10])

In [133]:
x.unsqueeze(1).shape

torch.Size([10, 1])

In [134]:
torch.arange(10).unsqueeze(0).unsqueeze(1).shape

torch.Size([1, 1, 10])

In [135]:
torch.arange(10).unsqueeze(0).squeeze(0).shape

torch.Size([10])